/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TRIP;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class AllData extends javax.swing.JInternalFrame {

    /**
     * Creates new form AllData
     */
    private JTable combinedTable;

    public AllData() {
        setTitle("Combined Data");
        setSize(800, 600);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        initComponents(); // Inisialisasi komponen GUI
        showTable(); // Tampilkan data di tabel
        
        jScrollPane1 = new javax.swing.JScrollPane();
        AllDataTable = new JTable();
        BacktoMenu = new javax.swing.JButton();

        // Konfigurasi JTable
        AllDataTable.setModel(new DefaultTableModel(
            new Object [][] {},
            new String [] {
                "No Pemesanan", "Nama", "Kontak", "Tempat", "Paket TRIP", "Jadwal", "Harga Paket Trip", "Pilihan Pembayaran", "Status Pembayaran"
            }
        ));
        jScrollPane1.setViewportView(AllDataTable);

        // Konfigurasi tombol kembali ke menu
        BacktoMenu.setText("Back To Menu");
        BacktoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BacktoMenuActionPerformed(evt);
            }
        });

        // Layout
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BacktoMenu)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BacktoMenu)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();

        // Tampilkan data di tabel
        showTable(); 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        AllDataTable = new javax.swing.JTable();
        BacktoMenu = new javax.swing.JButton();

        AllDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Pemesanan", "Nama ", "Kontak", "Tempat", "Paket TRIP", "Jadwal", "Harga Paket Trip", "Pilihan Pembayaran", "Status Pembayaran"
            }
        ));
        jScrollPane1.setViewportView(AllDataTable);

        BacktoMenu.setText("Back To Menu");
        BacktoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BacktoMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BacktoMenu)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BacktoMenu)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void BacktoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BacktoMenuActionPerformed
        MenuUtama Menu = new MenuUtama();
        Menu.setVisible(true);
        this.getDesktopPane().add(Menu);
        this.dispose();
    }//GEN-LAST:event_BacktoMenuActionPerformed

    public void showTable(){
        try {
            Statement stat = (Statement) CONECTIONDB.connectDatabase().createStatement();
            String sql = "SELECT c.customer_id, c.Customer, c.Contacts, d.Destinasi, d.PaketTrip, d.Jadwal, d.Harga, p.MetodePembayaran, p.payment " +
                         "FROM customer c " +
                         "JOIN destinasi d ON c.customer_id = d.customer_id " +
                         "JOIN payment p ON c.customer_id = p.customer_id";
            ResultSet rs = stat.executeQuery(sql);
            DefaultTableModel tableModel = (DefaultTableModel) AllDataTable.getModel();

            // Hapus semua baris sebelum menambahkan data baru
            tableModel.setRowCount(0);

            while (rs.next()) {
                tableModel.addRow(new Object[]{
                    rs.getString(1), rs.getString(2), rs.getString(3),
                    rs.getString(4), rs.getString(5), rs.getString(6),
                    rs.getString(7), rs.getString(8), rs.getString(9)
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(AllData.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AllDataTable;
    private javax.swing.JButton BacktoMenu;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
