/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TRIP;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class FrameUtama extends javax.swing.JFrame {

    /**
     * Creates new form FrameUtama
     */
    public FrameUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MENU = new javax.swing.JMenu();
        LOGINMENU = new javax.swing.JMenuItem();
        LOGOUTMENU = new javax.swing.JMenuItem();
        EXITMENU = new javax.swing.JMenuItem();
        KETERANGAN = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1086, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );

        MENU.setText("LOGIN MENU");

        LOGINMENU.setText("LOGIN ");
        LOGINMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGINMENUActionPerformed(evt);
            }
        });
        MENU.add(LOGINMENU);

        LOGOUTMENU.setText("LOGOUT");
        LOGOUTMENU.setEnabled(false);
        LOGOUTMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTMENUActionPerformed(evt);
            }
        });
        MENU.add(LOGOUTMENU);

        EXITMENU.setText("EXIT");
        EXITMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITMENUActionPerformed(evt);
            }
        });
        MENU.add(EXITMENU);

        jMenuBar1.add(MENU);

        KETERANGAN.setText("KETERANGAN ");
        jMenuBar1.add(KETERANGAN);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LOGINMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGINMENUActionPerformed
        DesktopPane.removeAll();;
        LoginMenu loginMenu = new LoginMenu();
        loginMenu.setVisible(true);
        DesktopPane.add(loginMenu);
        LOGINMENU.setEnabled(false);
        LOGOUTMENU.setEnabled(true);
    }//GEN-LAST:event_LOGINMENUActionPerformed

    private void LOGOUTMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTMENUActionPerformed
        DesktopPane.removeAll();
        LoginMenu loginMenu = new LoginMenu();
        loginMenu.setVisible(true);
        DesktopPane.add(loginMenu);
        LOGOUTMENU.setEnabled(false);
        LOGINMENU.setEnabled(true);

    }//GEN-LAST:event_LOGOUTMENUActionPerformed

    private void EXITMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITMENUActionPerformed
        int pilih = JOptionPane.showConfirmDialog(null, "Keluar Aplikasi",
               "Konfirmasi", JOptionPane.OK_CANCEL_OPTION);
        if(pilih == JOptionPane.OK_OPTION){
            System.exit(0);
        }else {
            JOptionPane.getRootFrame();
        }
    }//GEN-LAST:event_EXITMENUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenuItem EXITMENU;
    private javax.swing.JMenu KETERANGAN;
    private javax.swing.JMenuItem LOGINMENU;
    private javax.swing.JMenuItem LOGOUTMENU;
    private javax.swing.JMenu MENU;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
