/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TRIP;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class OrderMenu2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form OrderMenu2
     */
    public OrderMenu2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PaketTRIP = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NEXT = new javax.swing.JButton();
        HargaPaket = new javax.swing.JTextField();
        JadwalKeberangkatan = new javax.swing.JComboBox<>();
        LokasiDestinasi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jLabel10.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel10.setText("Data pesanan trip");

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        jLabel4.setText("Paket Trip");

        PaketTRIP.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        PaketTRIP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIHAN", "PAKET PLATINUM I", "PAKET PLATINUM II", "PAKET PLATINUM III", "PAKET SILVER I", "PAKET SILVER II", "PAKET SILVER III", "PAKET GOLD I", "PAKET GOLD II", "PAKET GOLD III", " " }));
        PaketTRIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaketTRIPActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        jLabel3.setText("Jadwal Keberangkatan");

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        jLabel2.setText("Harga Paket");

        NEXT.setText("Next");
        NEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEXTActionPerformed(evt);
            }
        });

        JadwalKeberangkatan.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        JadwalKeberangkatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIHAN", "Sabtu - Minggu ( 06 Juli 2024)", "Jumat - Sabtu ( 12 - 13 Juli 2024)", "Jumat - Minggu (26 - 28 Juli 2024)", " " }));
        JadwalKeberangkatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JadwalKeberangkatanActionPerformed(evt);
            }
        });

        LokasiDestinasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LokasiDestinasiActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        jLabel5.setText("Lokai Destinasi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(124, 124, 124))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JadwalKeberangkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LokasiDestinasi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PaketTRIP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(HargaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LokasiDestinasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HargaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PaketTRIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JadwalKeberangkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NEXT))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PaketTRIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaketTRIPActionPerformed
        switch(PaketTRIP.getSelectedIndex()){
            case 0 :
                HargaPaket.setText("");
                LokasiDestinasi.setText("");
                break;
            case 1 :
                HargaPaket.setText("450000");
                LokasiDestinasi.setText("GUNUNG BROMO");
                break;
            case 2 :
                HargaPaket.setText("700000");
                LokasiDestinasi.setText("GUNUNG RINJANI");
                break;
            case 3 :
                HargaPaket.setText("300000");
                LokasiDestinasi.setText("GUNUNG PRAU");
                break;
            case 4 :
                HargaPaket.setText("675000");
                LokasiDestinasi.setText("GUNUNG BROMO");
                break;
            case 5 :
                HargaPaket.setText("1200000");
                LokasiDestinasi.setText("GUNUNG RINJANI");
                break;
            case 6 :
                HargaPaket.setText("450000");
                LokasiDestinasi.setText("GUNUNG PRAU");
                break;
            case 7 :
                HargaPaket.setText("900000");
                LokasiDestinasi.setText("GUNUNG BROMO");
                break;
            case 8 :
                HargaPaket.setText("2000000");
                LokasiDestinasi.setText("GUNUNG RINJANI");
                break;
            case 9 :
                HargaPaket.setText("650000");
                LokasiDestinasi.setText("GUNUNG PRAU");
                break;    
        }
    }//GEN-LAST:event_PaketTRIPActionPerformed

    private void NEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEXTActionPerformed
        try{
        String sql = "INSERT INTO destinasi(Destinasi, PaketTrip, Jadwal, Harga) VALUES (?,?,?,?)";
        Connection conn = (Connection)CONECTIONDB.connectDatabase();
        PreparedStatement pst = conn.prepareStatement(sql);
        
        pst.setString(1, (String) LokasiDestinasi.getText());
        pst.setString(2, (String) PaketTRIP.getSelectedItem());
        pst.setString(3, (String) JadwalKeberangkatan.getSelectedItem());
         pst.setInt(4, Integer.parseInt(HargaPaket.getText())); // Pastikan HargaPaket adalah angka
        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan!");
                
        OrderMenu3 Menu3 = new OrderMenu3();
        Menu3.setVisible(true);
        this.getDesktopPane().add(Menu3);
        this.dispose();
        
    } catch (SQLException ex) {
        Logger.getLogger(OrderMenu2.class.getName()).log(Level.SEVERE, null, ex);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Harga Paket harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_NEXTActionPerformed

    private void JadwalKeberangkatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JadwalKeberangkatanActionPerformed
        
    }//GEN-LAST:event_JadwalKeberangkatanActionPerformed

    private void LokasiDestinasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LokasiDestinasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LokasiDestinasiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HargaPaket;
    private javax.swing.JComboBox<String> JadwalKeberangkatan;
    private javax.swing.JTextField LokasiDestinasi;
    private javax.swing.JButton NEXT;
    private javax.swing.JComboBox<String> PaketTRIP;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
