/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TRIP;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class OrderMenu extends javax.swing.JInternalFrame {

    /**
     * Creates new form OrderMenu
     */
    public OrderMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        CustemerNameTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        NoTelpCustomer = new javax.swing.JLabel();
        ContactCustomerTxt = new javax.swing.JTextField();
        DataCustemerOrder = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setTitle("FORM PEMESANAN");

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        jLabel2.setText("Nama Customer");

        CustemerNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustemerNameTxtActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel9.setText("Data Diri Custemer");

        NoTelpCustomer.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        NoTelpCustomer.setText("Nomor Telepon");

        ContactCustomerTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactCustomerTxtActionPerformed(evt);
            }
        });

        DataCustemerOrder.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        DataCustemerOrder.setText("NEXT");
        DataCustemerOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataCustemerOrderActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 8)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("#Diisi Dengan Angka");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(NoTelpCustomer))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(CustemerNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                            .addComponent(ContactCustomerTxt))
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(DataCustemerOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(196, 196, 196))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CustemerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoTelpCustomer)
                    .addComponent(ContactCustomerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(DataCustemerOrder)
                .addGap(113, 113, 113))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustemerNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustemerNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustemerNameTxtActionPerformed

    private void ContactCustomerTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactCustomerTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactCustomerTxtActionPerformed

    private void DataCustemerOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataCustemerOrderActionPerformed
     try {
        // SQL for the first table
        String sql = "INSERT INTO customer (Customer, Contacts) VALUES (?, ?)";
        Connection conn = (Connection) CONECTIONDB.connectDatabase();
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, CustemerNameTxt.getText());
        pst.setString(2, ContactCustomerTxt.getText());

        // Execute the first insert statement
        pst.executeUpdate();
        // Optionally show a success message
        JOptionPane.showMessageDialog(this, "Data berhasil disimpan.");

        // Navigate to the next window or do further actions
        OrderMenu2 Menu2 = new OrderMenu2();
        Menu2.setVisible(true);
        this.getDesktopPane().add(Menu2);
        this.dispose();

    } catch (SQLException ex) {
        Logger.getLogger(OrderMenu.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menyimpan data:\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_DataCustemerOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ContactCustomerTxt;
    private javax.swing.JTextField CustemerNameTxt;
    private javax.swing.JButton DataCustemerOrder;
    private javax.swing.JLabel NoTelpCustomer;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
