/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TRIP;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class OrderMenu3 extends javax.swing.JInternalFrame {

    /**
     * Creates new form OrderMenu3
     */
    public OrderMenu3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ComboBoxMetodePembayaran = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        ComboBoxTotalPembayaran = new javax.swing.JComboBox<>();
        FINISH = new javax.swing.JButton();

        jLabel10.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel10.setText("Data Pembayaran Pesanan");

        jLabel1.setText("Metode Pembayaran");

        ComboBoxMetodePembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIHAN", "DANA", "OVO", "SHOPEEPAY", "BANK BRI", "BANK BNI", " " }));

        jLabel2.setText("Total Pembayaran");

        ComboBoxTotalPembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIHAN", "DP 50%", "LUNAS" }));

        FINISH.setText("FINISH");
        FINISH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FINISHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboBoxMetodePembayaran, 0, 286, Short.MAX_VALUE)
                            .addComponent(ComboBoxTotalPembayaran, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FINISH, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel10)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ComboBoxMetodePembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ComboBoxTotalPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(FINISH)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FINISHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FINISHActionPerformed
        try {
        // Perbaiki query SQL menjadi dua parameter
        String sql = "INSERT INTO payment (payment, MetodePembayaran) VALUES (?, ?)";
        Connection conn = (Connection)CONECTIONDB.connectDatabase();
        
        // Persiapkan statement
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, (String) ComboBoxMetodePembayaran.getSelectedItem());
        pst.setString(2, (String) ComboBoxTotalPembayaran.getSelectedItem());
        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan!");
        
        // Tampilkan menu utama
        MenuUtama MU = new MenuUtama();
        MU.setVisible(true);
        this.getDesktopPane().add(MU);
        this.dispose();
        
    } catch (SQLException ex) {
        Logger.getLogger(OrderMenu3.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_FINISHActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxMetodePembayaran;
    private javax.swing.JComboBox<String> ComboBoxTotalPembayaran;
    private javax.swing.JButton FINISH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
