/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TRIP;

/**
 *
 * @author ASUS
 */
public class PriceListMenu extends javax.swing.JInternalFrame {

    /**
     * Creates new form PriceListMenu
     */
    public PriceListMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BACKTOMENUBUTTON = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();

        setTitle("PRICE LIST");

        BACKTOMENUBUTTON.setText("BACK");
        BACKTOMENUBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKTOMENUBUTTONActionPerformed(evt);
            }
        });

        jLabel1.setText("---Gunung Bromo---- \n1. Paket Platinum Rp. 450.000,00 \n    Fasilitas     = Jeep Tiket, wisata Guide dan tour leader Dokumentasi \n2. Paket Silver Rp. 675.000,00 \n    Fasilitas     = Jeep, Tiket wisata, Guide dan tour leader, Dokumentasi, Makan 1x\n3. Paket Gold Rp. 900.000,00\n    Fasilitas = Tranportasi PP (malang), Jeep, Tiket wisata, \n    Guide dan tour leader, Dokumentasi, Makan 2x, Snack 1x");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "GUNUNG RINJANI", "Paket Platinum 700k", "Simaksi", "Asuransi TNGR", "P3K", "Guide lokal", "Tenda", "Makan 1x", " ", "Paket Silver 1.200k", "Simaksi", "Asuransi TNGR", "P3K", "Guide lokal", "Tenda", "Transport Lombok - Basecamp PP", "Makan 2x", "Dokumentasi", " ", "Paket Gold 2.000k", "Simaksi", "Asuransi TNGR", "P3K", "Guide lokal", "Tenda", "Transport Lombok - Basecamp PP", "Makan selama pendakian", "Penginapan dan makan sebelum pendakian", "Dokumentasi", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Gunung Bromo", "Paket Platinum 450k", "Jeep", "Tiket wisata", "Guide dan tour leader", "Dokumentasi", " ", "Paket Silver 675K", "Jeep", "Tiket wisata", "Guide dan tour leader", "Dokumentasi", "Makan 1x", " ", "Paket Gold 900k", "Tranportasi PP (malang) ", "Jeep", "Tiket wisata", "Guide dan tour leader", "Dokumentasi", "Makan 2x", "Snack 1x", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Gunung Prau ", "Paket Platinum 300K", "Simaksi", "Asuransi TNGP", "Guide", "P3K", " ", "Paket Silver 450k", "Simaksi", "Asuransi TNGP", "Guide", "P3K", "Tenda", "Makan 2x", "Dokumentasi", " ", "Paket Gold 650k", "Tranport Wonosobo - Basecamp PP", "Simaksi", "Asuransi TNGP", "Guide", "P3K", "Tenda", "Makan 2x", "Snack 1x", "Dokumentasi", " ", "[1/7 21.00] Ti22A Zaki: Gunung Bromo", "Paket Platinum 450k", "Jeep", "Tiket wisata", "Guide dan tour leader", "Dokumentasi", " ", "Paket Silver 675K", "Jeep", "Tiket wisata", "Guide dan tour leader", "Dokumentasi", "Makan 1x", " ", "Paket Gold 900k", "Tranportasi PP (malang) ", "Jeep", "Tiket wisata", "Guide dan tour leader", "Dokumentasi", "Makan 2x", "Snack 1x", " ", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BACKTOMENUBUTTON))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BACKTOMENUBUTTON)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BACKTOMENUBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKTOMENUBUTTONActionPerformed
        MenuUtama menuUtama = new MenuUtama();
        menuUtama.setVisible(true);
        this.getDesktopPane().add(menuUtama);
        this.dispose();
    }//GEN-LAST:event_BACKTOMENUBUTTONActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACKTOMENUBUTTON;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
