/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TRIP;

/**
 *
 * @author ASUS
 */
public class ShowTabelDataPesanan extends javax.swing.JInternalFrame {

    /**
     * Creates new form DataPesanan
     */
    public ShowTabelDataPesanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DataCustomer = new javax.swing.JButton();
        PaketPesanan = new javax.swing.JButton();
        Payment = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        BackToMenu = new javax.swing.JButton();

        DataCustomer.setText("Data Custemer");
        DataCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataCustomerActionPerformed(evt);
            }
        });

        PaketPesanan.setText("Paket Pesanan");
        PaketPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaketPesananActionPerformed(evt);
            }
        });

        Payment.setText("Payment");
        Payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentActionPerformed(evt);
            }
        });

        jButton4.setText("Show All Data");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        BackToMenu.setText("Back To Menu");
        BackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DataCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Payment, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaketPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(BackToMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataCustomer)
                    .addComponent(jButton4))
                .addGap(32, 32, 32)
                .addComponent(PaketPesanan)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(Payment))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(BackToMenu)))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PaketPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaketPesananActionPerformed
        DataPaketDestinasi Order = new DataPaketDestinasi();
        Order.setVisible(true);
        this.getDesktopPane().add(Order);
        this.dispose();
    }//GEN-LAST:event_PaketPesananActionPerformed

    private void PaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentActionPerformed
        DataPayment Pay = new DataPayment();
        Pay.setVisible(true);
        this.getDesktopPane().add(Pay);
        this.dispose();
    }//GEN-LAST:event_PaymentActionPerformed

    private void DataCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataCustomerActionPerformed
        DataCustomer DCust = new DataCustomer();
        DCust.setVisible(true);
        this.getDesktopPane().add(DCust);
        this.dispose();
    }//GEN-LAST:event_DataCustomerActionPerformed

    private void BackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToMenuActionPerformed
        MenuUtama Menu = new MenuUtama();
        Menu.setVisible(true);
        this.getDesktopPane().add(Menu);
        this.dispose();
    }//GEN-LAST:event_BackToMenuActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        AllData AD = new AllData();
        AD.setVisible(true);
        this.getDesktopPane().add(AD);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToMenu;
    private javax.swing.JButton DataCustomer;
    private javax.swing.JButton PaketPesanan;
    private javax.swing.JButton Payment;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
